services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - not_network
    expose:
      - "5432"
    ports:
      - "5431:5432"
    restart: always
    env_file:
      - .env

  redis:
    image: redis:latest
    networks:
      - not_network
    expose:
      - "6379"
    restart: always
    env_file:
      - .env

  bot:
    build: 
      context: .
    depends_on:
      - db
      - redis
    networks:
      - not_network
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: always
    env_file:
      - .env

networks:
  not_network:
    driver: bridge

volumes:
  postgres_data: